name: going-nowhere # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: After a hole in the road appears, you are stuck in a mysterious dream town
description: |
  After a hole in the road appears, you are stuck in a mysterious dream town. Discover the meaning of it all as you traverse the town and meet the strange inhabitants.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  going-nowhere_icon.png
title: Going Nowhere

apps:
  going-nowhere:
    command: GoingNowhere.x86
parts:
  going-nowhere:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      going-nowhere: build/
      going-nowhere.1: man/man1/

architectures:
  - build-on: amd64

